site_name: "dmGuide"
nav:
  - Home: index.md
  - About: about.md
  - App:
    - LazyVim:
      - Download: App/LazyVim/download.md 
      - Keybindings: App/LazyVim/keybindings.md 
    - Rclone:
      - Download: App/Rclone/configuration.md 
      - Configuration: App/Rclone/configuration.md  
    - Clash:  
      - Configuration: App/Clash/configuration.md 
    - Mkdocs:
      - Configuration: App/Mkdocs/configuration.md
    - Anaconda:  
      - Configuration: App/Anaconda/configuration.md
    - Waybar:  
      - Configuration: App/Waybar/configuration.md  
theme: 
  name: mkdocs
site_author: Downmars
