site_name: "dmGuide"
nav:
  - Home: index.md
  - About: about.md
  - App:
    - Configuration:
      - Configuration: App/Configuration/configuration.md
    - LazyVim:
      - Download: App/LazyVim/download.md 
      - Keybindings: App/LazyVim/keybindings.md 
    - Rclone:
      - Download: App/Rclone/configuration.md 
      - Configuration: App/Rclone/configuration.md  
    - Clash:  
      - Configuration: App/Clash/configuration.md 
    - Mkdocs:
      - Configuration: App/Mkdocs/configuration.md
    - Anaconda:  
      - Configuration: App/Anaconda/configuration.md
    - Waybar:  
      - Configuration: App/Waybar/configuration.md  
    - Go-musicfox:
      - Configuration: App/Go-musicfox/configuration.md  
    - Screenshot:
      - Configuration: App/Screenshot/configuration.md  
    - Screenrecord:
      - Configuration: App/Screenrecord/configuration.md
    - Pasteboard:
      - Configuration: App/Pasteboard/configuration.md
    - Download:
      - Configuration: App/Download/configuration.md
    - Dotfiles:
      - Configuration: App/Dotfiles/configuration.md
    - FzfMenu:
      - Configuration: App/FzfMenu/configuration.md
    - GptAnswer:
      - Answer: App/GptAnswer/index.md
theme: 
  name: mkdocs
site_author: Downmars
